<?php

namespace App\Service;

use GeoIp2\Database\Reader;

class GeoIPService
{
    private string $countryDbPath;
    private string $cityDbPath;
    private string $asnDbPath;

    public function __construct(string $countryDbPath, string $cityDbPath, string $asnDbPath)
    {
        $this->countryDbPath = $countryDbPath;
        $this->cityDbPath = $cityDbPath;
        $this->asnDbPath = $asnDbPath;
    }

    public function lookupCountry(string $ip)
    {
        if (!file_exists($this->countryDbPath)) {
            return null;
        }

        try {
            $reader = new Reader($this->countryDbPath);
            return $reader->country($ip);
        } catch (\Exception $e) {
            return null;
        }
    }

    public function lookupCity(string $ip)
    {
        if (!file_exists($this->cityDbPath)) {
            return null;
        }

        try {
            $reader = new Reader($this->cityDbPath);
            return $reader->city($ip);
        } catch (\Exception $e) {
            return null;
        }
    }

    public function lookupASN(string $ip)
    {
        if (!file_exists($this->asnDbPath)) {
            return null;
        }

        try {
            $reader = new Reader($this->asnDbPath);
            return $reader->asn($ip);
        } catch (\Exception $e) {
            return null;
        }
    }

    public function getCountryIso3ByIso2($iso2)
    {
        // All countries
        static $country_list = [
            'AF' => 'AFG',
            'AX' => 'ALA',
            'AL' => 'ALB',
            'DZ' => 'DZA',
            'AS' => 'ASM',
            'AD' => 'AND',
            'AO' => 'AGO',
            'AI' => 'AIA',
            'AQ' => 'ATA',
            'AG' => 'ATG',
            'AR' => 'ARG',
            'AM' => 'ARM',
            'AW' => 'ABW',
            'AU' => 'AUS',
            'AT' => 'AUT',
            'AZ' => 'AZE',
            'BS' => 'BHS',
            'BH' => 'BHR',
            'BD' => 'BGD',
            'BB' => 'BRB',
            'BY' => 'BLR',
            'BE' => 'BEL',
            'BZ' => 'BLZ',
            'BJ' => 'BEN',
            'BM' => 'BMU',
            'BT' => 'BTN',
            'BO' => 'BOL',
            'BA' => 'BIH',
            'BW' => 'BWA',
            'BV' => 'BVT',
            'BR' => 'BRA',
            'IO' => 'IOT',
            'BN' => 'BRN',
            'BG' => 'BGR',
            'BF' => 'BFA',
            'BI' => 'BDI',
            'CV' => 'CPV',
            'KH' => 'KHM',
            'CM' => 'CMR',
            'CA' => 'CAN',
            'BQ' => 'BES',
            'KY' => 'CYM',
            'CF' => 'CAF',
            'TD' => 'TCD',
            'CL' => 'CHL',
            'CN' => 'CHN',
            'CX' => 'CXR',
            'CC' => 'CCK',
            'CO' => 'COL',
            'KM' => 'COM',
            'CG' => 'COG',
            'CD' => 'COD',
            'CK' => 'COK',
            'CR' => 'CRI',
            'HR' => 'HRV',
            'CU' => 'CUB',
            'CW' => 'CUW',
            'CY' => 'CYP',
            'CZ' => 'CZE',
            'CI' => 'CIV',
            'DK' => 'DNK',
            'DJ' => 'DJI',
            'DM' => 'DMA',
            'DO' => 'DOM',
            'EC' => 'ECU',
            'EG' => 'EGY',
            'SV' => 'SLV',
            'GQ' => 'GNQ',
            'ER' => 'ERI',
            'EE' => 'EST',
            'SZ' => 'SWZ',
            'ET' => 'ETH',
            'FK' => 'FLK',
            'FO' => 'FRO',
            'FJ' => 'FJI',
            'FI' => 'FIN',
            'FR' => 'FRA',
            'GF' => 'GUF',
            'PF' => 'PYF',
            'TF' => 'ATF',
            'GA' => 'GAB',
            'GM' => 'GMB',
            'GE' => 'GEO',
            'DE' => 'DEU',
            'GH' => 'GHA',
            'GI' => 'GIB',
            'GR' => 'GRC',
            'GL' => 'GRL',
            'GD' => 'GRD',
            'GP' => 'GLP',
            'GU' => 'GUM',
            'GT' => 'GTM',
            'GG' => 'GGY',
            'GN' => 'GIN',
            'GW' => 'GNB',
            'GY' => 'GUY',
            'HT' => 'HTI',
            'HM' => 'HMD',
            'HN' => 'HND',
            'HK' => 'HKG',
            'HU' => 'HUN',
            'IS' => 'ISL',
            'IN' => 'IND',
            'ID' => 'IDN',
            'IR' => 'IRN',
            'IQ' => 'IRQ',
            'IE' => 'IRL',
            'IM' => 'IMN',
            'IL' => 'ISR',
            'IT' => 'ITA',
            'JM' => 'JAM',
            'JP' => 'JPN',
            'JE' => 'JEY',
            'JO' => 'JOR',
            'KZ' => 'KAZ',
            'KE' => 'KEN',
            'KI' => 'KIR',
            'KP' => 'PRK',
            'KR' => 'KOR',
            'XK' => 'XKX',
            'KW' => 'KWT',
            'KG' => 'KGZ',
            'LA' => 'LAO',
            'LV' => 'LVA',
            'LB' => 'LBN',
            'LS' => 'LSO',
            'LR' => 'LBR',
            'LY' => 'LBY',
            'LI' => 'LIE',
            'LT' => 'LTU',
            'LU' => 'LUX',
            'MO' => 'MAC',
            'MK' => 'MKD',
            'MG' => 'MDG',
            'MW' => 'MWI',
            'MY' => 'MYS',
            'MV' => 'MDV',
            'ML' => 'MLI',
            'MT' => 'MLT',
            'MH' => 'MHL',
            'MQ' => 'MTQ',
            'MR' => 'MRT',
            'MU' => 'MUS',
            'YT' => 'MYT',
            'MX' => 'MEX',
            'FM' => 'FSM',
            'MD' => 'MDA',
            'MC' => 'MCO',
            'MN' => 'MNG',
            'ME' => 'MNE',
            'MS' => 'MSR',
            'MA' => 'MAR',
            'MZ' => 'MOZ',
            'MM' => 'MMR',
            'NA' => 'NAM',
            'NR' => 'NRU',
            'NP' => 'NPL',
            'NL' => 'NLD',
            'NC' => 'NCL',
            'NZ' => 'NZL',
            'NI' => 'NIC',
            'NE' => 'NER',
            'NG' => 'NGA',
            'NU' => 'NIU',
            'NF' => 'NFK',
            'MP' => 'MNP',
            'NO' => 'NOR',
            'OM' => 'OMN',
            'PK' => 'PAK',
            'PW' => 'PLW',
            'PS' => 'PSE',
            'PA' => 'PAN',
            'PG' => 'PNG',
            'PY' => 'PRY',
            'PE' => 'PER',
            'PH' => 'PHL',
            'PN' => 'PCN',
            'PL' => 'POL',
            'PT' => 'PRT',
            'PR' => 'PRI',
            'QA' => 'QAT',
            'RE' => 'REU',
            'RO' => 'ROU',
            'RU' => 'RUS',
            'RW' => 'RWA',
            'BL' => 'BLM',
            'SH' => 'SHN',
            'KN' => 'KNA',
            'LC' => 'LCA',
            'MF' => 'MAF',
            'PM' => 'SPM',
            'VC' => 'VCT',
            'WS' => 'WSM',
            'SM' => 'SMR',
            'ST' => 'STP',
            'SA' => 'SAU',
            'SN' => 'SEN',
            'RS' => 'SRB',
            'SC' => 'SYC',
            'SL' => 'SLE',
            'SG' => 'SGP',
            'SX' => 'SXM',
            'SK' => 'SVK',
            'SI' => 'SVN',
            'SB' => 'SLB',
            'SO' => 'SOM',
            'ZA' => 'ZAF',
            'GS' => 'SGS',
            'SS' => 'SSD',
            'ES' => 'ESP',
            'LK' => 'LKA',
            'SD' => 'SDN',
            'SR' => 'SUR',
            'SJ' => 'SJM',
            'SE' => 'SWE',
            'CH' => 'CHE',
            'SY' => 'SYR',
            'TW' => 'TWN',
            'TJ' => 'TJK',
            'TZ' => 'TZA',
            'TH' => 'THA',
            'TL' => 'TLS',
            'TG' => 'TGO',
            'TK' => 'TKL',
            'TO' => 'TON',
            'TT' => 'TTO',
            'TN' => 'TUN',
            'TR' => 'TUR',
            'TM' => 'TKM',
            'TC' => 'TCA',
            'TV' => 'TUV',
            'UM' => 'UMI',
            'UG' => 'UGA',
            'UA' => 'UKR',
            'AE' => 'ARE',
            'GB' => 'GBR',
            'US' => 'USA',
            'UY' => 'URY',
            'UZ' => 'UZB',
            'VU' => 'VUT',
            'VA' => 'VAT',
            'VE' => 'VEN',
            'VN' => 'VNM',
            'VG' => 'VGB',
            'VI' => 'VIR',
            'WF' => 'WLF',
            'EH' => 'ESH',
            'YE' => 'YEM',
            'ZM' => 'ZMB',
            'ZW' => 'ZWE',

        ];

        $iso2 = strtoupper(trim($iso2)); // Sanitize input

        return $country_list[$iso2] ?? null;
    }

    public function getCurrencyByIso2($iso2)
    {
        static $currencies = [
            'AF' => ['name' => 'Afghan Afghani', 'code' => 'AFN', 'symbol' => '؋'],
            'AL' => ['name' => 'Albanian Lek', 'code' => 'ALL', 'symbol' => 'L'],
            'DZ' => ['name' => 'Algerian Dinar', 'code' => 'DZD', 'symbol' => 'د.ج'],
            'AD' => ['name' => 'Euro', 'code' => 'EUR', 'symbol' => '€'],
            'AO' => ['name' => 'Angolan Kwanza', 'code' => 'AOA', 'symbol' => 'Kz'],
            'AR' => ['name' => 'Argentine Peso', 'code' => 'ARS', 'symbol' => '$'],
            'AM' => ['name' => 'Armenian Dram', 'code' => 'AMD', 'symbol' => '֏'],
            'AU' => ['name' => 'Australian Dollar', 'code' => 'AUD', 'symbol' => '$'],
            'AT' => ['name' => 'Euro', 'code' => 'EUR', 'symbol' => '€'],
            'AZ' => ['name' => 'Azerbaijani Manat', 'code' => 'AZN', 'symbol' => '₼'],
            'BS' => ['name' => 'Bahamian Dollar', 'code' => 'BSD', 'symbol' => '$'],
            'BH' => ['name' => 'Bahraini Dinar', 'code' => 'BHD', 'symbol' => '.د.ب'],
            'BD' => ['name' => 'Bangladeshi Taka', 'code' => 'BDT', 'symbol' => '৳'],
            'BB' => ['name' => 'Barbadian Dollar', 'code' => 'BBD', 'symbol' => '$'],
            'BY' => ['name' => 'Belarusian Ruble', 'code' => 'BYN', 'symbol' => 'Br'],
            'BE' => ['name' => 'Euro', 'code' => 'EUR', 'symbol' => '€'],
            'BZ' => ['name' => 'Belize Dollar', 'code' => 'BZD', 'symbol' => '$'],
            'BJ' => ['name' => 'West African CFA Franc', 'code' => 'XOF', 'symbol' => 'Fr'],
            'BM' => ['name' => 'Bermudian Dollar', 'code' => 'BMD', 'symbol' => '$'],
            'BT' => ['name' => 'Bhutanese Ngultrum', 'code' => 'BTN', 'symbol' => 'Nu.'],
            'BO' => ['name' => 'Bolivian Boliviano', 'code' => 'BOB', 'symbol' => 'Bs.'],
            'BA' => ['name' => 'Convertible Mark', 'code' => 'BAM', 'symbol' => 'KM'],
            'BW' => ['name' => 'Botswana Pula', 'code' => 'BWP', 'symbol' => 'P'],
            'BR' => ['name' => 'Brazilian Real', 'code' => 'BRL', 'symbol' => 'R$'],
            'BN' => ['name' => 'Brunei Dollar', 'code' => 'BND', 'symbol' => '$'],
            'BG' => ['name' => 'Bulgarian Lev', 'code' => 'BGN', 'symbol' => 'лв'],
            'BF' => ['name' => 'West African CFA Franc', 'code' => 'XOF', 'symbol' => 'Fr'],
            'BI' => ['name' => 'Burundian Franc', 'code' => 'BIF', 'symbol' => 'Fr'],
            'KH' => ['name' => 'Cambodian Riel', 'code' => 'KHR', 'symbol' => '៛'],
            'CM' => ['name' => 'Central African CFA Franc', 'code' => 'XAF', 'symbol' => 'Fr'],
            'CA' => ['name' => 'Canadian Dollar', 'code' => 'CAD', 'symbol' => '$'],
            'CV' => ['name' => 'Cape Verdean Escudo', 'code' => 'CVE', 'symbol' => '$'],
            'KY' => ['name' => 'Cayman Islands Dollar', 'code' => 'KYD', 'symbol' => '$'],
            'CF' => ['name' => 'Central African CFA Franc', 'code' => 'XAF', 'symbol' => 'Fr'],
            'TD' => ['name' => 'Central African CFA Franc', 'code' => 'XAF', 'symbol' => 'Fr'],
            'CL' => ['name' => 'Chilean Peso', 'code' => 'CLP', 'symbol' => '$'],
            'CN' => ['name' => 'Chinese Yuan', 'code' => 'CNY', 'symbol' => '¥'],
            'CO' => ['name' => 'Colombian Peso', 'code' => 'COP', 'symbol' => '$'],
            'KM' => ['name' => 'Comorian Franc', 'code' => 'KMF', 'symbol' => 'Fr'],
            'CG' => ['name' => 'Central African CFA Franc', 'code' => 'XAF', 'symbol' => 'Fr'],
            'CD' => ['name' => 'Congolese Franc', 'code' => 'CDF', 'symbol' => 'Fr'],
            'CR' => ['name' => 'Costa Rican Colón', 'code' => 'CRC', 'symbol' => '₡'],
            'HR' => ['name' => 'Croatian Kuna', 'code' => 'HRK', 'symbol' => 'kn'],
            'CU' => ['name' => 'Cuban Peso', 'code' => 'CUP', 'symbol' => '$'],
            'CZ' => ['name' => 'Czech Koruna', 'code' => 'CZK', 'symbol' => 'Kč'],
            'DK' => ['name' => 'Danish Krone', 'code' => 'DKK', 'symbol' => 'kr'],
            'DJ' => ['name' => 'Djiboutian Franc', 'code' => 'DJF', 'symbol' => 'Fr'],
            'DM' => ['name' => 'East Caribbean Dollar', 'code' => 'XCD', 'symbol' => '$'],
            'DO' => ['name' => 'Dominican Peso', 'code' => 'DOP', 'symbol' => '$'],
            'EC' => ['name' => 'United States Dollar', 'code' => 'USD', 'symbol' => '$'],
            'EG' => ['name' => 'Egyptian Pound', 'code' => 'EGP', 'symbol' => '£'],
            'SV' => ['name' => 'United States Dollar', 'code' => 'USD', 'symbol' => '$'],
            'GQ' => ['name' => 'Central African CFA Franc', 'code' => 'XAF', 'symbol' => 'Fr'],
            'ER' => ['name' => 'Eritrean Nakfa', 'code' => 'ERN', 'symbol' => 'Nkf'],
            'EE' => ['name' => 'Euro', 'code' => 'EUR', 'symbol' => '€'],
            'ET' => ['name' => 'Ethiopian Birr', 'code' => 'ETB', 'symbol' => 'Br'],
            'FJ' => ['name' => 'Fiji Dollar', 'code' => 'FJD', 'symbol' => '$'],
            'FI' => ['name' => 'Euro', 'code' => 'EUR', 'symbol' => '€'],
            'FR' => ['name' => 'Euro', 'code' => 'EUR', 'symbol' => '€'],
            'GA' => ['name' => 'Central African CFA Franc', 'code' => 'XAF', 'symbol' => 'Fr'],
            'GM' => ['name' => 'Gambian Dalasi', 'code' => 'GMD', 'symbol' => 'D'],
            'GE' => ['name' => 'Georgian Lari', 'code' => 'GEL', 'symbol' => '₾'],
            'DE' => ['name' => 'Euro', 'code' => 'EUR', 'symbol' => '€'],
            'GH' => ['name' => 'Ghanaian Cedi', 'code' => 'GHS', 'symbol' => '₵'],
            'GR' => ['name' => 'Euro', 'code' => 'EUR', 'symbol' => '€'],
            'GT' => ['name' => 'Guatemalan Quetzal', 'code' => 'GTQ', 'symbol' => 'Q'],
            'GN' => ['name' => 'Guinean Franc', 'code' => 'GNF', 'symbol' => 'Fr'],
            'GY' => ['name' => 'Guyanese Dollar', 'code' => 'GYD', 'symbol' => '$'],
            'HT' => ['name' => 'Haitian Gourde', 'code' => 'HTG', 'symbol' => 'G'],
            'HN' => ['name' => 'Honduran Lempira', 'code' => 'HNL', 'symbol' => 'L'],
            'HK' => ['name' => 'Hong Kong Dollar', 'code' => 'HKD', 'symbol' => '$'],
            'HU' => ['name' => 'Hungarian Forint', 'code' => 'HUF', 'symbol' => 'Ft'],
            'IS' => ['name' => 'Icelandic Króna', 'code' => 'ISK', 'symbol' => 'kr'],
            'IN' => ['name' => 'Indian Rupee', 'code' => 'INR', 'symbol' => '₹'],
            'ID' => ['name' => 'Indonesian Rupiah', 'code' => 'IDR', 'symbol' => 'Rp'],
            'IR' => ['name' => 'Iranian Rial', 'code' => 'IRR', 'symbol' => '﷼'],
            'IQ' => ['name' => 'Iraqi Dinar', 'code' => 'IQD', 'symbol' => 'ع.د'],
            'IE' => ['name' => 'Euro', 'code' => 'EUR', 'symbol' => '€'],
            'IL' => ['name' => 'Israeli New Shekel', 'code' => 'ILS', 'symbol' => '₪'],
            'IT' => ['name' => 'Euro', 'code' => 'EUR', 'symbol' => '€'],
            'JM' => ['name' => 'Jamaican Dollar', 'code' => 'JMD', 'symbol' => '$'],
            'JP' => ['name' => 'Japanese Yen', 'code' => 'JPY', 'symbol' => '¥'],
            'JO' => ['name' => 'Jordanian Dinar', 'code' => 'JOD', 'symbol' => 'د.ا'],
            'KZ' => ['name' => 'Kazakhstani Tenge', 'code' => 'KZT', 'symbol' => '₸'],
            'KE' => ['name' => 'Kenyan Shilling', 'code' => 'KES', 'symbol' => 'Sh'],
            'KI' => ['name' => 'Australian Dollar', 'code' => 'AUD', 'symbol' => '$'],
            'KW' => ['name' => 'Kuwaiti Dinar', 'code' => 'KWD', 'symbol' => 'د.ك'],
            'KG' => ['name' => 'Kyrgyzstani Som', 'code' => 'KGS', 'symbol' => 'лв'],
            'LA' => ['name' => 'Lao Kip', 'code' => 'LAK', 'symbol' => '₭'],
            'LV' => ['name' => 'Euro', 'code' => 'EUR', 'symbol' => '€'],
            'LB' => ['name' => 'Lebanese Pound', 'code' => 'LBP', 'symbol' => 'ل.ل'],
            'LS' => ['name' => 'Lesotho Loti', 'code' => 'LSL', 'symbol' => 'L'],
            'LR' => ['name' => 'Liberian Dollar', 'code' => 'LRD', 'symbol' => '$'],
            'LY' => ['name' => 'Libyan Dinar', 'code' => 'LYD', 'symbol' => 'ل.د'],
            'LI' => ['name' => 'Swiss Franc', 'code' => 'CHF', 'symbol' => 'CHF'],
            'LT' => ['name' => 'Euro', 'code' => 'EUR', 'symbol' => '€'],
            'LU' => ['name' => 'Euro', 'code' => 'EUR', 'symbol' => '€'],
            'MO' => ['name' => 'Macanese Pataca', 'code' => 'MOP', 'symbol' => 'P'],
            'MK' => ['name' => 'Macedonian Denar', 'code' => 'MKD', 'symbol' => 'ден'],
            'MG' => ['name' => 'Malagasy Ariary', 'code' => 'MGA', 'symbol' => 'Ar'],
            'MW' => ['name' => 'Malawian Kwacha', 'code' => 'MWK', 'symbol' => 'MK'],
            'MY' => ['name' => 'Malaysian Ringgit', 'code' => 'MYR', 'symbol' => 'RM'],
            'MV' => ['name' => 'Maldivian Rufiyaa', 'code' => 'MVR', 'symbol' => 'Rf'],
            'ML' => ['name' => 'West African CFA Franc', 'code' => 'XOF', 'symbol' => 'Fr'],
            'MT' => ['name' => 'Euro', 'code' => 'EUR', 'symbol' => '€'],
            'MH' => ['name' => 'US Dollar', 'code' => 'USD', 'symbol' => '$'],
            'MQ' => ['name' => 'Euro', 'code' => 'EUR', 'symbol' => '€'],
            'MR' => ['name' => 'Mauritanian Ouguiya', 'code' => 'MRU', 'symbol' => 'UM'],
            'MU' => ['name' => 'Mauritian Rupee', 'code' => 'MUR', 'symbol' => '₨'],
            'MX' => ['name' => 'Mexican Peso', 'code' => 'MXN', 'symbol' => '$'],
            'FM' => ['name' => 'US Dollar', 'code' => 'USD', 'symbol' => '$'],
            'MD' => ['name' => 'Moldovan Leu', 'code' => 'MDL', 'symbol' => 'L'],
            'MC' => ['name' => 'Euro', 'code' => 'EUR', 'symbol' => '€'],
            'MN' => ['name' => 'Mongolian Tögrög', 'code' => 'MNT', 'symbol' => '₮'],
            'ME' => ['name' => 'Euro', 'code' => 'EUR', 'symbol' => '€'],
            'MA' => ['name' => 'Moroccan Dirham', 'code' => 'MAD', 'symbol' => 'د.م.'],
            'MZ' => ['name' => 'Mozambican Metical', 'code' => 'MZN', 'symbol' => 'MT'],
            'MM' => ['name' => 'Burmese Kyat', 'code' => 'MMK', 'symbol' => 'K'],
            'NA' => ['name' => 'Namibian Dollar', 'code' => 'NAD', 'symbol' => '$'],
            'NR' => ['name' => 'Australian Dollar', 'code' => 'AUD', 'symbol' => '$'],
            'NP' => ['name' => 'Nepalese Rupee', 'code' => 'NPR', 'symbol' => '₨'],
            'NL' => ['name' => 'Euro', 'code' => 'EUR', 'symbol' => '€'],
            'NZ' => ['name' => 'New Zealand Dollar', 'code' => 'NZD', 'symbol' => '$'],
            'NI' => ['name' => 'Nicaraguan Córdoba', 'code' => 'NIO', 'symbol' => 'C$'],
            'NE' => ['name' => 'West African CFA Franc', 'code' => 'XOF', 'symbol' => 'Fr'],
            'NG' => ['name' => 'Nigerian Naira', 'code' => 'NGN', 'symbol' => '₦'],
            'NO' => ['name' => 'Norwegian Krone', 'code' => 'NOK', 'symbol' => 'kr'],
            'OM' => ['name' => 'Omani Rial', 'code' => 'OMR', 'symbol' => '﷼'],
            'PK' => ['name' => 'Pakistani Rupee', 'code' => 'PKR', 'symbol' => '₨'],
            'PW' => ['name' => 'US Dollar', 'code' => 'USD', 'symbol' => '$'],
            'PA' => ['name' => 'Panamanian Balboa', 'code' => 'PAB', 'symbol' => 'B/.'],
            'PG' => ['name' => 'Papua New Guinean Kina', 'code' => 'PGK', 'symbol' => 'K'],
            'PY' => ['name' => 'Paraguayan Guaraní', 'code' => 'PYG', 'symbol' => '₲'],
            'PE' => ['name' => 'Peruvian Sol', 'code' => 'PEN', 'symbol' => 'S/'],
            'PH' => ['name' => 'Philippine Peso', 'code' => 'PHP', 'symbol' => '₱'],
            'PL' => ['name' => 'Polish Złoty', 'code' => 'PLN', 'symbol' => 'zł'],
            'PT' => ['name' => 'Euro', 'code' => 'EUR', 'symbol' => '€'],
            'QA' => ['name' => 'Qatari Riyal', 'code' => 'QAR', 'symbol' => '﷼'],
            'RO' => ['name' => 'Romanian Leu', 'code' => 'RON', 'symbol' => 'lei'],
            'RU' => ['name' => 'Russian Ruble', 'code' => 'RUB', 'symbol' => '₽'],
            'RW' => ['name' => 'Rwandan Franc', 'code' => 'RWF', 'symbol' => 'Fr'],
            'KN' => ['name' => 'East Caribbean Dollar', 'code' => 'XCD', 'symbol' => '$'],
            'LC' => ['name' => 'East Caribbean Dollar', 'code' => 'XCD', 'symbol' => '$'],
            'VC' => ['name' => 'East Caribbean Dollar', 'code' => 'XCD', 'symbol' => '$'],
            'WS' => ['name' => 'Samoan Tālā', 'code' => 'WST', 'symbol' => 'T'],
            'SM' => ['name' => 'Euro', 'code' => 'EUR', 'symbol' => '€'],
            'ST' => ['name' => 'São Tomé and Príncipe Dobra', 'code' => 'STN', 'symbol' => 'Db'],
            'SA' => ['name' => 'Saudi Riyal', 'code' => 'SAR', 'symbol' => '﷼'],
            'SN' => ['name' => 'West African CFA Franc', 'code' => 'XOF', 'symbol' => 'Fr'],
            'RS' => ['name' => 'Serbian Dinar', 'code' => 'RSD', 'symbol' => 'дин.'],
            'SC' => ['name' => 'Seychellois Rupee', 'code' => 'SCR', 'symbol' => '₨'],
            'SL' => ['name' => 'Sierra Leonean Leone', 'code' => 'SLL', 'symbol' => 'Le'],
            'SG' => ['name' => 'Singapore Dollar', 'code' => 'SGD', 'symbol' => '$'],
            'SK' => ['name' => 'Euro', 'code' => 'EUR', 'symbol' => '€'],
            'SI' => ['name' => 'Euro', 'code' => 'EUR', 'symbol' => '€'],
            'SB' => ['name' => 'Solomon Islands Dollar', 'code' => 'SBD', 'symbol' => '$'],
            'SO' => ['name' => 'Somali Shilling', 'code' => 'SOS', 'symbol' => 'Sh'],
            'ZA' => ['name' => 'South African Rand', 'code' => 'ZAR', 'symbol' => 'R'],
            'KR' => ['name' => 'South Korean Won', 'code' => 'KRW', 'symbol' => '₩'],
            'ES' => ['name' => 'Euro', 'code' => 'EUR', 'symbol' => '€'],
            'LK' => ['name' => 'Sri Lankan Rupee', 'code' => 'LKR', 'symbol' => '₨'],
            'SD' => ['name' => 'Sudanese Pound', 'code' => 'SDG', 'symbol' => '£'],
            'SR' => ['name' => 'Surinamese Dollar', 'code' => 'SRD', 'symbol' => '$'],
            'SE' => ['name' => 'Swedish Krona', 'code' => 'SEK', 'symbol' => 'kr'],
            'CH' => ['name' => 'Swiss Franc', 'code' => 'CHF', 'symbol' => 'CHF'],
            'SY' => ['name' => 'Syrian Pound', 'code' => 'SYP', 'symbol' => '£'],
            'TW' => ['name' => 'New Taiwan Dollar', 'code' => 'TWD', 'symbol' => 'NT$'],
            'TJ' => ['name' => 'Tajikistani Somoni', 'code' => 'TJS', 'symbol' => 'ЅМ'],
            'TZ' => ['name' => 'Tanzanian Shilling', 'code' => 'TZS', 'symbol' => 'Sh'],
            'TH' => ['name' => 'Thai Baht', 'code' => 'THB', 'symbol' => '฿'],
            'TL' => ['name' => 'US Dollar', 'code' => 'USD', 'symbol' => '$'],
            'TG' => ['name' => 'West African CFA Franc', 'code' => 'XOF', 'symbol' => 'Fr'],
            'TO' => ['name' => 'Tongan Paʻanga', 'code' => 'TOP', 'symbol' => 'T$'],
            'TT' => ['name' => 'Trinidad and Tobago Dollar', 'code' => 'TTD', 'symbol' => '$'],
            'TN' => ['name' => 'Tunisian Dinar', 'code' => 'TND', 'symbol' => 'د.ت'],
            'TR' => ['name' => 'Turkish Lira', 'code' => 'TRY', 'symbol' => '₺'],
            'TM' => ['name' => 'Turkmenistan Manat', 'code' => 'TMT', 'symbol' => 'm'],
            'UG' => ['name' => 'Ugandan Shilling', 'code' => 'UGX', 'symbol' => 'Sh'],
            'UA' => ['name' => 'Ukrainian Hryvnia', 'code' => 'UAH', 'symbol' => '₴'],
            'AE' => ['name' => 'United Arab Emirates Dirham', 'code' => 'AED', 'symbol' => 'د.إ'],
            'GB' => ['name' => 'British Pound Sterling', 'code' => 'GBP', 'symbol' => '£'],
            'US' => ['name' => 'US Dollar', 'code' => 'USD', 'symbol' => '$'],
            'UY' => ['name' => 'Uruguayan Peso', 'code' => 'UYU', 'symbol' => '$'],
            'UZ' => ['name' => 'Uzbekistan Som', 'code' => 'UZS', 'symbol' => "so'm"],
            'VU' => ['name' => 'Vanuatu Vatu', 'code' => 'VUV', 'symbol' => 'VT'],
            'VA' => ['name' => 'Euro', 'code' => 'EUR', 'symbol' => '€'],
            'VE' => ['name' => 'Venezuelan Bolívar', 'code' => 'VES', 'symbol' => 'Bs.'],
            'VN' => ['name' => 'Vietnamese Dong', 'code' => 'VND', 'symbol' => '₫'],
            'YE' => ['name' => 'Yemeni Rial', 'code' => 'YER', 'symbol' => '﷼'],
            'ZM' => ['name' => 'Zambian Kwacha', 'code' => 'ZMW', 'symbol' => 'ZK'],
            'ZW' => ['name' => 'Zimbabwean Dollar', 'code' => 'ZWL', 'symbol' => '$'],
        ];

        $iso2 = strtoupper(trim($iso2));
        return $currencies[$iso2] ?? null;
    }

}
